# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: okdocker/pynode:3.6-latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install CLI AWS tools
          command: |
            pip install awscli --upgrade --user
            pip install awsebcli --upgrade --user
            export PATH=~/.local/bin:$PATH  # required because not in path by default

      - run:
          name: deploy api
          command: |
            chmod +x api/deploy.sh
            .api/deploy.sh

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "admin/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: deploy admin
          command: |
            yarn install
            chmod +x admin/deploy.sh && ./admin/deploy.sh 

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "admin/package.json" }}
