# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: okdocker/pynode:3.6-latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install AWS / expo tools
          command: |
            pip install awscli --upgrade --user
            pip install awsebcli --upgrade --user
            yarn global add expo-cli

      - run:
          name: deploy api
          working_directory: api
          command: |
            export PATH=~/.local/bin:$PATH
            chmod +x deploy.sh
            ./deploy.sh

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "admin/package.json" }}-{{ checksum "website/package.json"}}-{{ checksum "app/package.json"}}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install workspace dependencies
          command: yarn install

      - run:
          name: deploy admin
          working_directory: admin
          command: |
            export PATH=~/.local/bin:$PATH
            chmod +x deploy.sh
            ./deploy.sh 

      - run:
          name: deploy website
          working_directory: website
          command: |
            export PATH=~/.local/bin:$PATH
            chmod +x deploy.sh
            ./deploy.sh 

      - run:
          name: deploy app
          working_directory: app
          command: |
            yarn
            echo "logging to expo"
            expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
            echo "publishing new app version"
            expo publish --non-interactive

      - save_cache:
          paths:
            - node_modules
            - website/node_modules
            - admin/node_modules
            - app/node_modules
          key: v1-dependencies-{{ checksum "admin/package.json" }}-{{ checksum "website/package.json" }}-{{ checksum "app/package.json" }}
